# Generated by Django 4.2.11 on 2024-04-21 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='image',
        ),
    ]
