# Generated by Django 4.2.11 on 2024-04-22 03:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_category_remove_listings_location_alter_listings_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
