# Generated by Django 4.2.11 on 2024-04-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listings_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='title',
            field=models.CharField(max_length=32),
        ),
    ]
